$file = 'c:\Users\solin\Downloads\Hemanth_b_E309drGtPne-1773079189463\mobile_app\lib\main.dart'
# Use UTF8 with BOM to ensure it's interpreted correctly by the OS/editor
$utf8 = New-Object System.Text.UTF8Encoding($true)
$content = [System.IO.File]::ReadAllText($file, $utf8)

# Common corruption patterns
$content = $content -replace 'â€“', '-'
$content = $content -replace 'âœ“', 'Check'
$content = $content -replace 'â• ', '='
$content = $content -replace 'â• ', '='
$content = $content -replace 'Ã²', '^2'
$content = $content -replace 'xÂ²', 'x^2'
$content = $content -replace 'âˆ«', 'integral'
$content = $content -replace 'âˆ’', '-'
$content = $content -replace 'ðŸ”¢', '🔢'
$content = $content -replace 'ðŸ“Œ', '📌'
$content = $content -replace 'ðŸ”£', '🔣'
$content = $content -replace 'Ï€', 'pi'
$content = $content -replace 'â­•', '⭕'
$content = $content -replace 'ðŸŒ€', '🌀'
$content = $content -replace 'â —', '!'
$content = $content -replace 'ðŸ”µ', '🔵'
$content = $content -replace 'âˆš', 'sqrt'
$content = $content -replace 'ðŸ”º', '🔺'
$content = $content -replace 'ðŸ“ˆ', '📈'
$content = $content -replace 'ðŸª™', '🪙'
$content = $content -replace 'ðŸ”±', '🔱'
$content = $content -replace 'ðŸ’»', '💻'
$content = $content -replace 'ðŸ“Š', '📊'
$content = $content -replace 'â¬¡', '⬡'
$content = $content -replace 'ðŸ”²', '🔲'
$content = $content -replace 'âš¡', '⚡'
$content = $content -replace 'ðŸ’¡', '💡'
$content = $content -replace 'ðŸš€', '🚀'
$content = $content -replace 'ðŸ”‹', '🔋'
$content = $content -replace 'ðŸ’ª', '💪'
$content = $content -replace 'ðŸŒ ', '🌍'
$content = $content -replace 'ðŸ ƒ', '🏃'
$content = $content -replace 'ðŸ§­', '🧭'
$content = $content -replace 'ðŸŒŠ', '🌊'
$content = $content -replace 'ðŸ”Œ', '🔌'
$content = $content -replace 'ðŸ”§', '🔧'
$content = $content -replace 'ðŸ‡®ðŸ‡³', '🇮🇳'
$content = $content -replace 'ðŸªž', '🪞'
$content = $content -replace 'ðŸ¤œ', '🤜'
$content = $content -replace 'ðŸ§²', '🧲'
$content = $content -replace 'ðŸ”‡', '🔇'
$content = $content -replace 'ðŸ«§', '🫧'
$content = $content -replace 'âš—ï¸ ', '⚗️'
$content = $content -replace 'ðŸ’§', '💧'
$content = $content -replace 'ðŸ§ª', '🧪'
$content = $content -replace 'ðŸŒ¬ï¸ ', '🌬️'
$content = $content -replace 'ðŸ§‚', '🧂'
$content = $content -replace 'ðŸ”¬', '🔬'
$content = $content -replace 'ðŸ¤ ', '🤝'
$content = $content -replace 'ðŸŽˆ', '🎈'
$content = $content -replace 'ðŸŒŸ', '🌟'
$content = $content -replace 'ðŸ‡', '🥇'
$content = $content -replace 'ðŸ”´', '🔴'
$content = $content -replace 'ðŸŒ¡ï¸ ', '🌡️'
$content = $content -replace 'ðŸ’Ž', '💎'
$content = $content -replace 'ðŸ ž', '🍞'
$content = $content -replace 'ðŸ”—', '🔗'
$content = $content -replace 'ðŸŒ¿', '🌿'
$content = $content -replace 'ðŸ“–', '📖'
$content = $content -replace 'ðŸ”„', '🔄'
$content = $content -replace 'ðŸ ·ï¸ ', '🏷️'

[System.IO.File]::WriteAllText($file, $content, $utf8)
Write-Host "Encoding cleanup done."
